### ISSUE TITLE
Setting temperature

### ISSUE THREAD

**Issue by smadds** [bisand/node-red-contrib-panasonic-comfort-cloud#5]
Hi. Thanks for creating this - looks like a great start. Connected to our Panasonic aircon straight away.

Do you have any plans to add the ability to turn it on/off and set the temperature? 

It would then be REALLY useful.....

**Comment by bisand** [comment]
Hi. Thanks for showing interest in this module. I have no immediate plans for this feature, but since you are asking, I will take a look at it and do some research into the topic. I cannot guarantee a quick resolution, but will try to move it up on my list.

If you are familiar with node.js development, feel free to submit a pull request.

Regards,
André

**Comment by smadds** [comment]
Thanks, André. I wish I was a programmer, but am not - some web design and
sql is about my limit.

Happy to look through protocols though - where you able to find it
documented, or did you have to wireshark it?

Regards

Simon


*Simon Maddox*


[image: maddox_new_logo_wide_trans_500h.png]

*t:* 01737 887 657   |   *mob:* 07785 504 340   |   *w:* maddox.co.uk   |
*e:* ***@***.***

**Comment by smadds** [comment]
Looks like marc2016 has already created an npm node that includes setting would this help?

https://github.com/marc2016/panasonic-comfort-cloud-client

**Comment by bisand** [comment]
You are right about that. That is exactly the module I'm using in "node-red-contrib-panasonic-comfort-cloud". I will certainly try to find some time to implement setting of values. Feel free to suggest features you want me to prioritize first.

**Comment by smadds** [comment]
I think if you could create a 3rd node-red node that is the command one with the 8 functions Marc has implemented (e.g. the taking command as the topic and the value as the payload) that would be ideal. I see he has also created the enums for 'Auto', 'High' etc. 

If you wanted to do them 1 at a time the most important it turning it on & off ;)

**Comment by bisand** [comment]
I have now published a new version of "node-red-contrib-panasonic-comfort-cloud" (v1.0.1). This includes a command node that takes a JSON object for payload and sets the applicable config values for the selected device. I have also updated the readme to contain some kind of documentation on how to use the new node. It would be nice if you have time to take it for a spin and let me know what you think. I have tested it on my heat pump and it works for me.
Don't hesitate to submit bugs or improvements, for nodes and/or documentation.

Good luck!

**Comment by smadds** [comment]
That's amazing! Thank you so much for putting some time into this.

It's not working for me at the moment, but I'm sure we're close!

If I store account credentials, they work for the previous 2 nodes, but the new command one does not seem to be using them properly - I get this if I hook a debug node onto its output:
![image](https://user-images.githubusercontent.com/5259870/145042507-90621404-1042-4bbf-a1e6-bbc1a2c9bda4.png)

Another (much smaller) thing is your naming of the Device ID configuration field - it's the same on the Device status and the command nodes. Maybe rename the label to Device ID or GUID?
![image](https://user-images.githubusercontent.com/5259870/145043293-915fa7db-f179-4e05-b9fd-9304f165d3b5.png)

Thanks

**Comment by bisand** [comment]
I have done some more testing, and it seems to be working on my setup.. Could it be a faulty payload? Can you please provide the JSON object you injected in the payload. It should be in JSON format, not text. 
Use the JSON example below as a starting point. The Device ID could be set in either the JSON object or the node.
I have also changed the label to Device ID
```json
{
"deviceId": "CS-XXXXXXX+1234567890",
"operate": "On",
"operationMode": "Heat",
"ecoMode": "Auto",
"temperatureSet": 22,
"airSwingUD": "Mid",
"airSwingLR": "Mid",
"fanAutoMode": "AirSwingAuto",
"fanSpeed": "Auto"
}
```

**Comment by smadds** [comment]
Strange. I was just sending the GUID and operate JSON, using an inject node set to JSON payload.
{
"deviceId": "CS-XXXXXXX+1234567890",
"operate": "On",
}

I also tried adding the Device ID at the command node, but this did not work either.

I have just tried injecting the same packet that you did (with the guid updated to that of my A/C unit) but I'm still getting the 'tried 3 times' error.

When I look at the device status the responses are mainly starting with underscores. Is this the same for you?

07/12/2021, 23:20:10node: 74714f31.9e4aa
msg : Object
object
_msgid: "302963a4.8d04ec"
topic: ""
payload: object
_operate: 0
_operationMode: 3
_temperatureSet: 22
_fanSpeed: 0
_fanAutoMode: 1
_airSwingLR: 2
_airSwingUD: 2
_ecoMode: 0
_actualNanoe: 1
_ecoNavi: 0
_nanoe: 2
_iAuto: 0
_airDirection: 1
_ecoFunctionData: 0
_insideTemperature: 22
_outTemperature: 5
lastSettingMode: 0
airQuality: 0

I'm using Node-Red v1.0.2 on a RPi - maybe that's the issue?

**Comment by bisand** [comment]
It seemed to be a problem with the payload validation. Earlier versions of Node-Red was a little bit more picky when it comes accepting payloads in the flows, so the payload you sent contained an invalid JSON string (see comma after "on",). This made the JSON parsing to fail on your version.

I have improved that logic and tested in on Node-Red 1.0.2, and it seems to be running OK. I have also improved the error handling, so the error messages should be a little bit better now.

The underscores just indicates that the returned object is using private variables. That should be OK.

**Comment by smadds** [comment]
Thanks for the update. I've spent quite some time today trying to get the new version installed - with not much success.

I have switched to another instance of node-red - version 2.1.3 running on a RPi. The nodes install fine from Manage Palette, but when I configure and deploy the Command node disappears - missing from the flows tab and the library.

![image](https://user-images.githubusercontent.com/5259870/145310076-7fce260b-9957-4e07-b897-690ab0152305.png)

Any ideas?

**Comment by smadds** [comment]
![image](https://user-images.githubusercontent.com/5259870/145311155-e458b507-598c-439b-a65a-14f7b1c3e870.png)

**Comment by bisand** [comment]
I suspect the new problems you are experiencing is probably because I used optional chaining (?.) in an expression and that was not supported until Node.js until version 14, and I suspect your installation is using an earlier version. This expression has now been replaced by a more supported one. My bad! 
Try to install the new version (1.0.4) and see if it works now.

**Comment by smadds** [comment]
Hi André. Firstly, thanks again for putting time into this - I know how difficult this can be - especially if it is working for you!

The nodes install now and deploy fine, but I'm still getting the connection issue - just on the Command node:

![Screenshot 2021-12-09 102418](https://user-images.githubusercontent.com/5259870/145379772-cb00881c-86be-4e30-a96a-c1bff250acfe.png)
I've checked and the command is of course not getting through. I'm using your example json - just with the GUID line removed and with the Device ID put into the node configuration. It works on the Device status node.

There is 1 other thing I have noticed and don't understand. If I connect a debug node to the Device node with the debug set to show msg.payload it indicates an object, but is unable to expand it:
![Screenshot 2021-12-09 102144](https://user-images.githubusercontent.com/5259870/145380345-d1a012a1-b96a-45ee-a84c-5ff4262b9d48.png)

If I configure the debug node to show full msg object it works fine:
![Screenshot 2021-12-09 102252](https://user-images.githubusercontent.com/5259870/145380518-e7295d88-1f81-4635-8535-0ed802eebfd6.png)

Using msg.payload on the Groups status node works fine too. Not a big deal, but there must be something different in the Device Status node.

I'm using node-red within Docker (IOTStack build for RPi). Here is a dump of the log:

9 Dec 10:22:07 - [info] [mqtt-broker:Local] Connected to broker: mqtt://192.168.24.250:1883

9 Dec 10:22:14 - [info] [pcc-device:896b8e0501d6f750] true

9 Dec 10:23:08 - [info] [pcc-device:896b8e0501d6f750] true

9 Dec 10:23:28 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:30 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:34 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

9 Dec 10:23:34 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:36 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:40 - [info] [pcc-device:896b8e0501d6f750] true

9 Dec 10:23:40 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

9 Dec 10:23:40 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:42 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:23:45 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

9 Dec 10:23:45 - [error] [pcc-command:5f0e30c4443206f6] Error: Reached max retry count 3. Please check your credentials, or read the logs for more information.

9 Dec 10:24:34 - [info] [pcc-device:896b8e0501d6f750] true

9 Dec 10:25:21 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:22 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:26 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

9 Dec 10:25:26 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:28 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:32 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

9 Dec 10:25:32 - [info] [pcc-command:5f0e30c4443206f6] [object Object]

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 1

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 3

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 22

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 2

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:34 - [info] [pcc-command:5f0e30c4443206f6] 0

9 Dec 10:25:39 - [info] [pcc-command:5f0e30c4443206f6] Obtained a new access token.

**Comment by bisand** [comment]
Ok, I will have to do some research and maybe spin up a RPi with the same environment as you. Could you provide some details on the RPi environment you are using. Could you also try to spin up a Node-Red instance on your own PC with the latest Node.js LTS to see if you get the same result as on the Pi. What version of Node.js is running on the Pi?
In the meantime, I will conduct some analyzing and testing on my side to see if I can get the same results as you are getting.

**Comment by bisand** [comment]
@smadds, I've released a new version with (hopefully) improved error logging. Could you please try to install it to see if you get some more informative error messages? 
I really appreciate your help and patience on this matter. 
Thanks! :)

**Comment by smadds** [comment]
I think we're getting there - and I really appreciate the effort you are putting in.

The Device node now returns a recognisable object in msg.payload

The command node is still returning an error:

![image](https://user-images.githubusercontent.com/5259870/145597984-b2d74374-a4bd-47fe-96e7-45fdc5c71d5c.png)

This happens when I inject the demo json you supply (less the guid, which is in the node) or just a simple single command:

![image](https://user-images.githubusercontent.com/5259870/145598549-e5175611-d670-46fe-9197-8149303b46ad.png)


Logs:

10 Dec 15:23:22 - [error] [pcc-command:5f0e30c4443206f6] Error: An error ocurred while trying to set device parameter: ServiceError: Adapter internal error,
10 Dec 15:23:17 - [info] [pcc-command:5f0e30c4443206f6] [object Object],
10 Dec 15:23:19 - [info] [pcc-command:5f0e30c4443206f6] 1

**Comment by smadds** [comment]
These are the versions I am using:
NODE_RED_VERSION	v2.1.3
NODE_VERSION	12.22.7

**Comment by bisand** [comment]
Strange! I have also tested with node.js v12.22.7 with success.. Just a thought.. Could it be a firewall or something on your side that could be blocking HTTP POST calls?

**Comment by smadds** [comment]
I don't think its a firewall issue. I'm running the node-red from home on a domestic broadband - and the app works fine on my phone on the same wifi network. I can control the device from the phone app then see the status change from your device node.

I would be interested to see if you can connect to our aircon successfully. Happy to share the Comfort Cloud login privately with you. My Whatsapp is +447785504340

**Comment by smadds** [comment]
This is my test config:

[
    {
        "id": "adc583949d87ddd2",
        "type": "pcc-groups",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "comfortCloudConfig": "706049c58d4f7494",
        "x": 490,
        "y": 240,
        "wires": [
            [
                "2af5cbb33e0c537a"
            ]
        ]
    },
    {
        "id": "896b8e0501d6f750",
        "type": "pcc-device",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "comfortCloudConfig": "706049c58d4f7494",
        "deviceId": "CZ-CAPWFC1+B8B7F1B3E188",
        "x": 490,
        "y": 320,
        "wires": [
            [
                "aa12c69fb92fa59c"
            ]
        ]
    },
    {
        "id": "5f0e30c4443206f6",
        "type": "pcc-command",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "comfortCloudConfig": "706049c58d4f7494",
        "deviceId": "CZ-CAPWFC1+B8B7F1B3E188",
        "x": 500,
        "y": 400,
        "wires": [
            [
                "eb40479f8efc1bab"
            ]
        ]
    },
    {
        "id": "4e5343a98f8ba96c",
        "type": "inject",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 290,
        "y": 240,
        "wires": [
            [
                "adc583949d87ddd2"
            ]
        ]
    },
    {
        "id": "2af5cbb33e0c537a",
        "type": "debug",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 730,
        "y": 240,
        "wires": []
    },
    {
        "id": "7e62452fda91d936",
        "type": "inject",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 290,
        "y": 320,
        "wires": [
            [
                "896b8e0501d6f750"
            ]
        ]
    },
    {
        "id": "aa12c69fb92fa59c",
        "type": "debug",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 730,
        "y": 320,
        "wires": []
    },
    {
        "id": "eb40479f8efc1bab",
        "type": "debug",
        "z": "a5b7afd8.59ad6",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 730,
        "y": 400,
        "wires": []
    },
    {
        "id": "c2f11c7f373258f4",
        "type": "inject",
        "z": "a5b7afd8.59ad6",
        "name": "On",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"operate\":\"On\"}",
        "payloadType": "json",
        "x": 290,
        "y": 400,
        "wires": [
            [
                "5f0e30c4443206f6"
            ]
        ]
    },
    {
        "id": "2eb27b87980b5b92",
        "type": "inject",
        "z": "a5b7afd8.59ad6",
        "name": "Off",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"operate\":\"Off\"}",
        "payloadType": "json",
        "x": 290,
        "y": 460,
        "wires": [
            [
                "5f0e30c4443206f6"
            ]
        ]
    },
    {
        "id": "706049c58d4f7494",
        "type": "pcc-config",
        "name": "CC Panasonic Account"
    }
]

**Comment by bisand** [comment]
@smadds, Before going down the road of exchanging credentials, I would like you to try one more time. I have switched out the old API client with my own implementation, which also give me a lot more control over the different elements. This client leverages the built in https client in Node.js to communicate with the API.

The command node will now try to do some validation on the provided parameters and only send the parameters you define to the Comfort Cloud API. That will most likely rule out some incompatibility issues (I hope).

It would be nice if you could test it one more time.

Thanks!

**Comment by smadds** [comment]
Looks like we have some success here!

I'll do more testing tomorrow, but I am not getting errors and I can see that I'm able to change operate mode between 0 and 1 with my test setup. 

Thanks!

**Comment by bisand** [comment]
Have you had time to do some more testing?
Can we close this?

**Comment by smadds** [comment]
![image](https://user-images.githubusercontent.com/5259870/146562797-40b93da6-e532-4274-9f4f-851138d38e85.png)

I've tried, but looks like the Panasonic server is down at the moment!

**Comment by smadds** [comment]
Panasonic Comfort Cloud server working again today...

Yes, this looks good now - thanks for all the time you've put into it.

**Comment by bisand** [comment]
Perfect! Thank you for doing all the testing. Have a wonderful Christmas!
